"""Build manuscript/SI_v20.md from data/ and results/ (run after make_all.py)."""
import sys, pathlib, json
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import re
import pandas as pd
from biocarb.params import ROOT

D = ROOT / "data"; R = ROOT / "results"; OUT = ROOT / "manuscript" / "SI_v21.md"
MANUSCRIPT = ROOT / "manuscript" / "manuscript_v21.md"


def house_style(text: str) -> str:
    """Editorial conventions requested by the authors: deployment *scenarios* (not scales) and no reference to the
    superseded v19 draft."""
    reps = [(r"\bdeployment scales?\b", "deployment scenarios"), (r"\b[Ss]cale ([AB])\b", lambda m: f"{'S' if m.group(0)[0] == 'S' else 's'}cenario {m.group(1)}"),
            (r"\bsame-scale\b", "same-scenario"), (r"\b[Aa]t (dry-mix|ready-mix) scale\b", lambda m: f"{'I' if m.group(0)[0] == 'A' else 'i'}n the {m.group(1)} scenario"),
            (r"\bbetween scales\b", "between scenarios"), (r"\bcompare scales\b", "compare scenarios"), (r"\bdiffers by scale\b", "differs by scenario"),
            (r"\bat equal scale\b", "in the same scenario"), (r"\bscale against\b", "scenario against"), (r"\bat the same scale\b", "in the same scenario"),
            (r"\b(both|each|either|two|per|given|the same) scales?\b", lambda m: m.group(0).replace("scales", "scenarios").replace("scale", "scenario")),
            (r"\(v19\)", ""), (r"\(XRF; v19 Table 1\)", "(XRF)"), (r"; v19 Aspen model", "; Aspen Plus model, this work"),
            (r"\(v19 Table S4; ", "("), (r" \(v19 Table S5\)", ""), (r"Full list in the v19 SI workbook\.", "Full list in the supplementary workbook."),
            (r"v19 SI Table S\d+( note \d+)?", "laboratory and design basis, this work"), (r"v19 Table S?\d+[a-z]?", "this work"),
            (r"v19 Sec\. [\d.]+( \(confirmed\))?", "this work"), (r"v19 Fig\. \d[a-z]?", "Fig. 2"), (r"v19 TEA[^;,)\|]*", "TEA basis, this work"),
            (r"v19 lab mix", "laboratory mix, this work"), (r"v19 text", "this work"), (r"\bv19\b", "this work")]
    for pat, rep in reps:
        text = re.sub(pat, rep, text)
    return text


def md(df: pd.DataFrame, floatfmt="{:.4g}", index=False) -> str:
    df = df.copy()
    for c in df.columns:
        if pd.api.types.is_float_dtype(df[c]):
            df[c] = df[c].map(lambda x: "" if pd.isna(x) else floatfmt.format(x))
    df = df.fillna("")
    if index:
        df = df.reset_index()
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str(r[c]).replace("|", "/").replace("\n", " ") for c in cols) + " |")
    return "\n".join(lines)


def main():
    P = pd.read_csv(D / "parameters.csv"); TP = pd.read_csv(D / "tea_parameters.csv"); EQ = pd.read_csv(D / "equipment.csv")
    inv = pd.read_csv(R / "inventory.csv"); tot = pd.read_csv(R / "lca_totals.csv", index_col=0)
    stage = pd.read_csv(R / "lca_gwp_by_stage.csv", index_col=0); val = pd.read_csv(R / "lca_validation.csv")
    tea = pd.read_csv(R / "tea_summary.csv"); con = pd.read_csv(R / "tea_msp_contributions.csv"); eq = pd.read_csv(R / "tea_equipment.csv")
    mc = pd.read_csv(R / "montecarlo_summary.csv"); probs = pd.read_csv(R / "montecarlo_probabilities.csv"); probs.columns = ["comparison", "probability"]
    tor = pd.read_csv(R / "tornado_BC_B.csv"); der = pd.read_csv(R / "derived_quantities.csv"); mac = pd.read_csv(R / "mac.csv", index_col=0)
    lab = pd.read_csv(D / "lab_data.csv"); bench = json.load(open(R / "benchmark.json"))
    imap = pd.read_csv(D / "impact_factor_map.csv")

    s = []
    s.append("""---
title: "Supporting Information"
subtitle: "Biomolecule-regulated carbonation (BioCarb) as a drop-in supplementary cementitious material (SCM): harmonized life-cycle and techno-economic assessment"
---

[Author list and affiliations as in the main text]

**Contents.** Text S1 laboratory protocol · Text S2 inventory equations · Text S3 cement models · Text S4 TEA equations · Text S5 strength transfer (k-value) · Tables S1–S18.

All tables in this document are generated by `src/build_si.py` from the CSV files in `data/` and `results/` of the accompanying repository; every parameter carries its source in Tables S3 and S10.

# Text S1. Laboratory protocol (as performed; reported unchanged)

*RCF preparation.* Cement paste specimens (OPC, w/c per ASTM C305) were cured, crushed (gear crusher, 2–3 passes), dried at 105 °C for 1 h, crushed again (micropore crusher) and ball-milled to <75 µm. The resulting hydrated-paste powder is a **simulated RCF** (CaO 57.8 wt %%, Table S1); field demolition fines contain sand and aggregate dust and have lower CaO (Table S4).

*Carbonation (one laboratory batch).* 1650 g deionized water; 6.6 g tannic acid dissolved (0.4 wt %% of water; 2.0 wt %% of RCF); 330 g RCF added and stirred at 300 rpm for 60 min; CO~2~ bubbled at 7 L min^−1^ for 60 min with stirring; slurry separated on 5 µm filter paper; filtrate recycled to the next soaking step. Reported slurry mass balance : 550 g water + 330 g RCF + 132 g CO~2~ + 2.2 g TA = 1014.2 g. *Note:* the measured uptake is 0.365 kg CO~2~ kg^−1^ RCF (120 g per 330 g); the 132 g in the mass balance corresponds to 0.40 kg kg^−1^ and should be reconciled. The ratio 1650 g/330 g = 5.0 kg water per kg RCF; the main text quotes L/S = 1.67, which corresponds to the 550 g of water retained in the slurry per 330 g RCF. The model uses the parameter `ls` (Table S3) for process-water accounting; it is set to 1.67 pending clarification and its effect on tank sizing is small.

*Where TA is lost (Text S2, Eq. S4).* TA is dissolved in the process water. After carbonation the slurry is separated; the solids retain one third of the water (550/1650 g) and, with it, one third of the dissolved TA (2.2 g of 6.6 g), which leaves with the product and is not recovered. The filtrate (two thirds of water and TA) is recycled to soaking. Make-up TA therefore equals the retained fraction. This assumes TA does not adsorb on the carbonated solids; adsorption would increase the loss toward 100 %% (sensitivity range 0.33–1.0).

*Carbonation efficiency.* Thermogravimetric analysis (TGA) was run on the dried carbonated powder (TA Instruments TGA 550) under nitrogen at 15 °C min^−1^ from ambient temperature to 1000 °C; the mass loss between 550 and 850 °C is attributed to CO~2~ released by CaCO~3~ decomposition, and the sample mass at 950 °C is taken as m~0~. CE = n~CO2~/n~CaO~ = (Δm/M~CO2~)/((ω~CaO~/100)·m~0~/M~CaO~) × 100 %% (Eq. S0), where Δm is that mass loss and ω~CaO~ the CaO content of the uncarbonated RCF by XRF (Table S1); CE is therefore the fraction of **total** CaO present as carbonate, including carbonate that existed before the process. The CE at t = 0 (CE~0~ = 16–17 %%, Fig. 2a of the main text) is that pre-existing carbonate. Three quantities follow: (i) total carbonate CO~2~ in the product = CE × 0.454 = 0.365 kg kg^−1^ (the reported measurement); (ii) **newly fixed CO~2~** = (CE − CE~0~) × 0.454 = 0.288 kg kg^−1^, which is the only CO~2~ credited in the LCA (Eq. S1); (iii) conversion of the initially carbonatable CaO = (CE − CE~0~)/(1 − CE~0~) = 76 %%, the process-efficiency figure. The reported laboratory data are unchanged; only the interpretation used in the system model is (v20).

*Mortar.* 770 g OPC + 3100 g sand dry-mixed, BioCarb slurry (1014 g) added and mixed 3 min; control: 1100 g OPC, 3100 g sand, 550 g water. Cubes cured under standard conditions and tested at 3, 7 and 28 d (Fig. 2b of the main text).

# Text S2. Inventory equations (per kg of finished mortar)

| Eq. | Quantity | Expression |
|---|---|---|
| S1 | CO~2~ newly fixed | u = CaO~RCF~ × 44.01/56.08 × (CE − CE~0~); base 0.30 × 0.7848 × 0.635 = 0.149 kg kg^−1^ |
| S2 | CO~2~ supplied / vented | s = u/η~util~ ; v = s − u |
| S3 | Electricity co-product (functional unit) | E = s·m~RCF~ / r~cap~ / (1 + u·m~RCF~), r~cap~ = 0.910 kg CO~2~ kWh^−1^ |
| S4 | TA make-up | m~TA~ = d~TA~ · f~ret~ · m~RCF~ |
| S5 | Process make-up water | w~p~ = (L/S) · f~ret,w~ · m~RCF~ |
| S6 | Column blower | W = ΔP · V / η~blower~ ; V = 0.5535 m^3^ kg^−1^ CO~2~ (25 °C, 1 atm) |
| S7 | Drying (scale A) | Q = m~w~ · q~dry~ / 3.6 ; m~w~ = m~RCF~(1+u) · x/(1−x) |
| S8 | Mass normalization | all BioCarb flows ÷ (1 + u·m~RCF~) |
| S24 | Apparent carbonation efficiency of literature data (Table S17) | CE~app~ = u~lit~ / (CaO~lit~ × 44.01/56.08) |

Here m~RCF~ = binder × replacement = 0.2316 × 0.30 = 0.0695 kg (0.0688 kg after normalization). The functional unit for **all** systems is 1 kg mortar + E kWh electricity. In BioCarb systems E is delivered by the SubPC plant **with** capture (0.272 kg CO~2~e kWh^−1^; the captured CO~2~ is its co-product); in all other systems E is delivered by the same SubPC plant **without** capture (0.942 kg CO~2~e kWh^−1^), following the NETL CO~2~U system-expansion convention. The avoided emission from capturing the CO~2~ is therefore fully represented by the 0.942 − 0.272 kg CO~2~e kWh^−1^ difference (≈ 0.74 kg CO~2~e per kg CO~2~ captured after the capture energy penalty). Mineralized CO~2~ is **not** credited again (a −1 credit would double count); it is listed in Table S5 for information. CO~2~ that leaves the column unabsorbed (utilization < 1) is charged at +1. Because E scales with the CO~2~ supplied, the reference systems must be re-evaluated whenever a BioCarb parameter changes; all sweeps, tornado and Monte Carlo results in this SI are computed that way and GWP comparisons are reported as differences at equal functional unit.

# Text S3. Cement models

All cements are built from the same background datasets (Table S15): Type IL = 0.86 clinker + 0.11 limestone + 0.03 gypsum + 0.037 kWh grinding; LC3-50 = 0.50 clinker + 0.30 calcined clay + 0.15 limestone + 0.05 gypsum + 0.0337 kWh; the fly-ash mortar uses Type IL for 70 %% of the binder and fly ash (burden-free by-product under the cut-off system model, plus 0.005 kWh kg^−1^ handling) for 30 %%. Validation against independent EPDs and the ecoinvent US Portland dataset is given in Table S9; the ecoinvent hand-mixed on-site cement mortar dataset gives %.3f kg CO~2~e kg^−1^ (plus co-product electricity), compared with 0.206 for the Type IL mortar modelled here (the ecoinvent dataset uses Portland cement).

# Text S4. TEA equations

The discounted-cash-flow structure (equity share, loan terms, MACRS depreciation, working capital, start-up year) follows the methodologies described in Davis et al. (2014), reference 54 of the main text; equipment costing follows Towler and Sinnott (2013), reference 37.

| Eq. | Expression |
|---|---|
| S9 | Purchased cost, vendor basis: C = C~base~ (S/S~base~)^n^ · CEPCI~2024~/CEPCI~quote~ |
| S10 | Purchased cost, correlation: C = (a + b S^n^) · CEPCI~2024~/CEPCI~2010~ (Towler & Sinnott 2013, Table 7.2; CEPCI~2010~ = 550.8, CEPCI~2024~ = 796.2) |
| S11 | ISBL = 1.5 ΣC ; OSBL = 0.13 ISBL ; TDC = ISBL + OSBL + common plant ; FCI = 1.20 TDC ; TCI = 1.05 FCI |
| S12 | Loan = 0.60 TCI at 8 %% over 10 yr; MACRS 7-yr depreciation of FCI |
| S13 | Variable cost = Σ(flow × price); fixed = labor + 3 %% ISBL maintenance + 0.7 %% FCI insurance/tax |
| S14 | RCF rate m~RCF~ [t h^−1^] = m~RCF,kg~ × annual mortar / (2 shifts × 8 h d^−1^ × 250 d yr^−1^ = 4000 h) |
| S15 | Tank volume V = m~slurry~ · t~res~ /(1100 kg m^−3^ × 0.8), t~res~ = 1 h (soaking, carbonation) and 2 h (settling) |
| S16 | Agitator power 0.2 kW m^−3^ (min 5 kW), one per tank |
| S17 | Gas flow Q = s · m~RCF~ · 0.5535 m^3^ kg^−1^; column diameter from u~g~ = 0.05 m s^−1^ (min 0.3 m), H = 4 m, 8 mm CS shell + 20 %% for heads |
| S18 | Filter-press capacity V = m~cake~ · t~cycle~ / ρ~cake~, with m~cake~ the wet cake at 30 %% moisture (kg h^−1^), t~cycle~ = 1 h and ρ~cake~ = 2000 kg m^−3^; split into units within the 0.4–1.4 m^3^ range of the cost correlation (scale A only) |
| S19 | Dryer duty = water evaporated (kg h^−1^) (scale A only) |
| S20 | Conveyor 20 m; pump from slurry volumetric flow |
| S21 | MSP: Σ~t~ CF~t~/(1+IRR)^t^ = 0 with CF~0~ = −equity·TCI; CF~t~ = revenue − variable − fixed − loan payment − tax; tax = 21 %% × max(0, revenue − variable − fixed − depreciation − interest); year-1 production 90 %%; working capital recovered in year 20 |
| S22 | Marginal abatement cost = (MSP~x~ − MSP~IL~)/(GWP~IL~ − GWP~x~), same scenario |

*Basis and boundary of MSP.* MSP is a plant-gate price expressed per kg of mortar as mixed (w/b 0.50) so that it shares the LCA functional-unit denominator. At the dry-mix plant the product sold is a bagged premix (1 − 0.1158 = 0.884 kg per kg mortar); the price per kg of premix is MSP/0.884 (Table S13). Mixing water and mixer electricity at scale A, delivery at both scales, and site labor are outside the producer boundary and identical across binders at a given scale. Indicative customer-side adders (not modelled): site mixing with a 0.56 kW drum mixer at ~1.1 t h^−1^ per worker ≈ 0.9 h t^−1^ ≈ 2.5 ¢ kg^−1^ at $28 h^−1^ (scale A only); local delivery of wet mortar ≈ 0.5–1.0 ¢ kg^−1^ (scale B). On a delivered-and-mixed basis the dry-mix route is therefore more expensive than the gate MSP suggests relative to ready-mix.

# Text S5. Strength transfer (cementing efficiency)

Mortar-cube strength cannot be extrapolated to concrete directly. The cementing-efficiency (k-value) concept (EN 206; Smith 1967; Papadakis et al.) assigns the SCM an efficiency k such that strength follows the equivalent water–binder ratio w/(c + k·p). With one control point (w/b 0.50) and equal-or-higher 28-d strength at 30 %% replacement, the data imply k ≈ 1 at 28 d and lower at 3 d; a control strength–w/c curve is required to quantify k with uncertainty. Holding target strength constant, the binder demand becomes T = c~0~/(0.7 + 0.3k) (Eq. S23); for k = 0.6 the cement saving falls from 30 %% to ~20 %%. This is why replacement level is treated as a design variable and shaded beyond 30 %% in Fig. 6.
""" % bench["ecoinvent_hand_mixed_mortar_plus_coproduct_GWP"])

    s.append("\n# Table S1. Chemical composition (wt %) of OPC and simulated RCF (XRF; v19 Table 1)\n")
    s.append("| Oxide | SiO2 | Al2O3 | Fe2O3 | CaO | MgO | SO3 | K2O | TiO2 | LOI | Total |\n|---|---|---|---|---|---|---|---|---|---|---|\n| OPC | 13.36 | 2.90 | 3.24 | 65.19 | 3.68 | 3.97 | 0.69 | 0.24 | 6.73 | 100 |\n| RCF (hydrated paste) | 11.32 | 2.58 | 3.05 | 57.83 | 2.45 | 2.82 | 0.11 | 0.22 | 19.63 | 100 |")
    s.append("\n# Table S2. Deployment scenarios\n")
    s.append(md(TP[TP.name.isin(["plantA_tpy", "plantB_tpy", "op_hours", "plant_common_A_cost", "plant_common_B_cost", "labor_fte_common_A", "labor_fte_bc_A", "labor_fte_common_B", "labor_fte_bc_B"])][["name", "value", "unit", "description", "source"]]))
    s.append("\n# Table S3. Process and inventory parameters (data/parameters.csv). mc_dist/low/high define Monte Carlo ranges; `_sa` = sensitivity only.\n"); s.append(md(P))
    s.append("\n# Table S4. CaO content of recycled concrete fines in the literature\n")
    s.append("| Material | CaO (wt %) | Source |\n|---|---|---|\n| Waste concrete fine powder, 20 Korean recycling plants | 15–30 (road-aggregate plants 28–31; concrete-aggregate plants ~20) | Recycling 2025, 10, 17 |\n| Recycled waste concrete powder, China | 11.4 | Sci. Rep. 2024 (PMC11547463) |\n| Recycled concrete powder, Egypt | 20.5 | J. Eng. Appl. Sci. 2026 |\n| Crushed test-cube powder, Portugal (paste-rich) | 45.5 | Sci. Rep. 2026 |\n| Fines 0/2 from high-quality concrete pavers | 46.2 | Sustainability 2025, 17, 1506 |\n| Simulated RCF, this work (hydrated OPC paste) | 57.8 | Table S1 |\n| **Model base case (field RCF)** | **30 (range 15–45)** | — |")
    s.append("\n# Table S5. Life-cycle inventory per kg of mortar (results/inventory.csv)\n")
    s.append(md(inv[["scenario", "stage", "flow", "amount", "unit", "dataset", "equation"]], floatfmt="{:.4e}"))
    s.append("\n# Table S6. Tannic-acid extraction inventory used as proxy for purchased TA (per kg TA solution; v19 Aspen model)\n")
    s.append(md(P[P.name.str.startswith("ta_")][["name", "value", "unit", "description", "source"]]))
    s.append("\n# Table S7. Mobile jaw crushers (v19 Table S4; mean diesel 2.19 gal h^−1^ at 86 t h^−1^ → 1.116 × 10^−4^ kg diesel per kg concrete)\n")
    s.append("| Brand | Model | t/h (max) | Fuel (gal/h) | Cost (USD) |\n|---|---|---|---|---|\n| Barford | 750J | 150 | 3.0 | 329,500 |\n| RubbleCrusher | RC150T | 55 | 2.5 | 139,500 |\n| RubbleCrusher | RCJ65T | 55 | 2.4 | 160,000 |\n| Terex Evoquip | Bison 35 | 35 | 1.6 | 225,000 |\n| ARK | J-2416 | 55 | 1.6 | 180,000 |\n| ARK | J-1910 | 34 | 1.6 | 99,000 |\n| Omega | J1065T | 220 | 2.6 | 420,000 |")
    s.append("\n# Table S8. Ball-mill specific energy (v19 Table S5): 46 units (Hengxing, AGICO), 1.4–87 t h^−1^, mean 0.0337 kWh kg^−1^ (range 0.027–0.043). Individual unit specifications are available from the authors.\n")
    s.append("\n# Table S9. Validation of component-built cements (GWP)\n"); s.append(md(val))
    s.append("\n# Table S10. TEA parameters (data/tea_parameters.csv)\n"); s.append(md(TP))
    s.append("\n# Table S11. Equipment sizing and purchased costs (2024 USD; results/tea_equipment.csv; based on Towler & Sinnott (2013) Table 7.2 when feasible).\n")
    s.append(md(eq[["scenario", "item", "size", "size_unit", "n_units", "purchased_cost_2024", "basis"]], floatfmt="{:.3g}"))
    s.append("\n# Table S12. LCA results per functional unit (1 kg mortar + %.4f kWh electricity)\n" % der.loc[0, "value"]); s.append(md(tot, floatfmt="{:.4g}", index=True))
    s.append("\nGWP by contribution (kg CO~2~e kg^−1^):\n"); s.append(md(stage, floatfmt="{:.4f}", index=True))
    s.append("\n# Table S13. TEA results\n"); s.append(md(tea.drop(columns=["scale"]), floatfmt="{:.4g}"))
    s.append("\nMSP contributions (¢ kg^−1^):\n"); s.append(md(con.pivot_table(index="item", columns="scenario", values="cents_per_kg", aggfunc="sum"), floatfmt="{:.3f}", index=True))
    s.append("\nMarginal abatement cost (USD t^−1^ CO~2~e vs Type IL, same scale):\n"); s.append(md(mac, floatfmt="{:.0f}", index=True))
    s.append("\n# Table S14. Monte Carlo summary (n = 1000) and probabilities\n"); s.append(md(mc, floatfmt="{:.4g}")); s.append("\n"); s.append(md(probs, floatfmt="{:.3f}"))
    s.append("\n# Table S15. Background datasets (UUIDs; unit impact scores not redistributed)\n"); s.append(md(imap))
    bb = pd.read_csv(R / "base_results.csv", index_col=0).loc["BC_B"]
    s.append("\n# Table S16. Tornado analysis, BioCarb ready-mix (change from base GWP %.3f kg CO~2~e kg^−1^, MSP %.2f ¢ kg^−1^). dGWP_vs_FA and dMSP_vs_IL are changes of the margin over the same-scale fly-ash and Type IL mortars (Fig. 7a, b); dGWP and dMSP are changes of the BioCarb value itself.\n" % (bb["GWP"], bb["MSP"]))
    s.append(md(tor[["parameter", "bound", "value", "dGWP", "dGWP_vs_FA", "dMSP", "dMSP_vs_IL"]], floatfmt="{:.4f}"))
    s.append("\n# Derived quantities\n"); s.append(md(der, floatfmt="{:.5g}"))
    litn = pd.read_csv(R / "literature_uptake_normalized.csv"); abat = pd.read_csv(D / "abatement_cost_literature.csv")
    s.append("\n# Table S17. Literature CO~2~ uptake (Table 1) normalized to apparent carbonation efficiency (Eq. S24). Reference numbers refer to the main-text list.\n")
    s.append(md(litn[["ref_no", "reference", "feedstock", "feedstock_type", "cao_wt_pct", "cao_basis", "co2_uptake_kg_per_kg", "uptake_basis", "process", "theoretical_uptake_kg_per_kg", "apparent_CE_pct"]], floatfmt="{:.3g}"))
    s.append("\n# Table S18. Published abatement costs used in Fig. 8 and for context, converted to 2024 USD per t CO~2~ avoided (negative = net saving). The `perspective` column states who bears the cost: concrete producer buying cement and SCMs at market prices (comparable with this study), cement producer at clinker production cost (context only), or cement buyer under full pass-through of kiln CCS. `fig8` marks the rows drawn in Fig. 8.\n"); s.append(md(abat, floatfmt="{:.3g}"))
    mbl = pd.read_csv(R / "mac_by_baseline.csv")
    s.append("\nMarginal abatement cost against each same-scale reference mortar (USD t^−1^ CO~2~e; blank where the scenario does not abate relative to that reference):\n"); s.append(md(mbl, floatfmt="{:.4g}"))
    # Table 1 of the main text (generated here so it always matches data/literature_uptake.csv; references numbered)
    t1 = litn[litn.table1_order > 0].sort_values("table1_order").copy()
    t1["Ref."] = t1["ref_no"].map(lambda r: "this study" if str(r) == "this study" else f"^{r}^")
    t1 = t1[["technology", "condition", "raw_material", "cement_replacement", "product_use_t1", "uptake_shown", "carbonation_time", "agent", "Ref."]].rename(columns={
        "technology": "Technology", "condition": "Condition", "raw_material": "Raw material", "cement_replacement": "Cement replacement", "product_use_t1": "Product",
        "uptake_shown": "CO~2~ uptake (kg CO~2~ kg^−1^ SCM)", "carbonation_time": "Carbonation time", "agent": "Extraction agent"})
    tab = ("**Table 1.** Reported CO~2~ uptake of RCF and other alkaline wastes by carbonation, with the BioCarb laboratory and model values. "
           "Uptakes are the newly fixed CO~2~ as reported by each study, except Shen et al. (total carbonate); the BioCarb laboratory value is given as total carbonate "
           "with the newly fixed part in parentheses. Normalization to each feedstock's theoretical uptake (apparent carbonation efficiency, Eq. S24) is given in Table S17.\n\n" + md(t1))
    mp = MANUSCRIPT; mtxt = mp.read_text(encoding="utf-8")
    a = mtxt.index("<!-- TABLE1_START -->") + len("<!-- TABLE1_START -->"); b = mtxt.index("<!-- TABLE1_END -->")
    mp.write_text(house_style(mtxt[:a] + "\n" + tab + "\n" + mtxt[b:]), encoding="utf-8")   # explicit UTF-8: the locale default corrupts the file on Windows
    OUT.write_text(house_style("\n".join(s)).replace("same scale", "same scenario").replace("Deployment scales", "Deployment scenarios"), encoding="utf-8"); print("wrote", OUT)


if __name__ == "__main__":
    main()
